on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *' # runs every 5 minutes
    
jobs:
  update-history:
    runs-on: ubuntu-latest
    name: Update file history
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4    
        with:
          ref: fetch
          persist-credentials: true

      - name: Run container
        run: docker compose run --rm --build app

      - name: Adds main branch to the worktree
        run: |
          git fetch origin main
          git worktree add /tmp/main origin/main

      - name: Copy data to main
        run: |
          cp ./output/output.txt /tmp/main/output/output.txt

      - name: Commit changes
        run: |
          cd /tmp/main
          git switch -c main origin/main # creates a local branch main at HEAD origin/main
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add ./output/output.txt
          git commit -m "Update ping log [skip ci]" || echo "No changes to commit"
          git push origin main

