on:
  workflow_dispatch:
    
jobs:
  update-history:
    runs-on: ubuntu:latest
    steps:
      - name: Run
        uses: actions/checkout@v4    

      - name: build docker image
        uses: docker build -t app .

      - name: run scripts
        uses: docker run \
          --rm app \
          -v ${{ github.workspace }}/output:/app/output \
          ping -c 4 reddit.com >> ./output/output.txt

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add ./output/output.txt
          git commit -m "Update ping log [skip ci]" || echo "No changes to commit"
          git push

